Adding nxos_vxlan_vtep_vni
ansible/ansible-modules-core pull request #4674
Opened 2016-09-03 00:00 UTC by GGabriele

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
nxos_vxlan_vtep_vni

##### ANSIBLE VERSION
```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/']
```

##### SUMMARY
Creates a Virtual Network Identifier member (VNI)

2016-09-03 03:25 UTC, gregdek commented
Thanks again to @GGabriele. This module is going into community review.

We notice that you are one of the maintainers (@privateip, @GGabriele, @gundalow) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-05 16:02 UTC, gundalow commented on network/nxos/nxos_vxlan_vtep_vni.py
> +    argument_spec = dict(
There are more options defined here than in the `DOCUMENTATION:`

Any option specified in `extends_documentation_fragment: nxos` needs defining in `module_utils`, have a look at other network modules.

2016-09-05 16:04 UTC, gundalow commented on network/nxos/nxos_vxlan_vtep_vni.py
> +        mutually_exclusive_params = ['multicast_group',
Please look at examples of `mutually_exclusive`, this is built in validation,  e.g cloud/openstack/_keystone_user.py

2016-09-05 16:05 UTC, gundalow commented
needs_revision

2016-09-05 21:25 UTC, gregdek commented
Thanks @GGabriele for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-09 06:50 UTC, GGabriele commented
ready_for_review

2016-09-09 09:25 UTC, gregdek commented
Thanks @GGabriele. To the current maintainers, @jedelman8, @GGabriele, @privateip, @gundalow please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-12 14:39 UTC, gundalow commented
@GGabriele I may be missing it, but where is the documentation defined for the following options?

```
m_facts
state
include_defaults
config
save
```

2016-09-12 15:26 UTC, gregdek commented
Thanks @GGabriele for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-15 06:27 UTC, GGabriele commented
ready_for_review

2016-09-15 09:25 UTC, gregdek commented
Thanks @GGabriele. To the current maintainers, @jedelman8, @GGabriele, @privateip, @gundalow please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-15 10:48 UTC, gundalow commented on network/nxos/nxos_vxlan_vtep_vni.py
> +            - Specify to use or not the complete runnning configuration
s/runnning/running/

2016-09-15 10:50 UTC, gundalow commented on network/nxos/nxos_vxlan_vtep_vni.py
> +    include_defaults:
@privateip Are we standardising on `defaults:` or `include_defaults:` (Assuming this is the same thing)

2016-09-15 10:51 UTC, gundalow requested changes
needs_revision

2016-09-19 02:22 UTC, merged