BGP Module
ansible/ansible-modules-core pull request #4738
Opened 2016-09-08 03:39 UTC by amitsi

##### ISSUE TYPE

 
 - New Module Pull Request

##### COMPONENT NAME

BGP Module
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/pluribus-ansible/ansible/library']
```

##### SUMMARY

```

```

2016-09-08 09:25 UTC, gregdek commented
Thanks @amitsi for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-08 23:16 UTC, amitsi commented
ready_for_review

2016-09-09 03:25 UTC, gregdek commented
Thanks @amitsi for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-12 06:40 UTC, gundalow commented on network/netvisor/pn_vrouterbgp.py
> +            pn_password=dict(type='str'),
All password (and any other sensitive data) options need

`no_log=True`

2016-09-15 06:53 UTC, ashxjain commented
The previous push was accidentally done with --amend, because of which it had @privateip 's changes. Created a clean branch locally and then pushed to Github with --force to overwrite the existing branch (pn_ospf). This is the latest clean commit: ccf299d2eef53c8f66732ec740017608c4f62be1

2016-09-16 10:32 UTC, gundalow commented on network/netvisor/pn_vrouterbgp.py
> +  description: The CLI command run on the target node(s).
Missing `returned:` and `type:`

2016-09-16 10:33 UTC, gundalow commented on network/netvisor/pn_vrouterbgp.py
> +            pn_multiprotocol=dict(type='bool',
This isn't a `bool` if it accepts choices=['ipv4-unicast', 'ipv6-unicast']

I think you mean `type:'str'`

2016-09-16 10:57 UTC, gundalow requested changes

2016-09-16 12:11 UTC, gundalow commented on network/netvisor/pn_vrouterbgp.py
> +            pn_multiprotocol=dict(type='bool',
Please check this then I can merge

2016-09-16 12:11 UTC, gundalow commented
needs_revision

2016-09-16 13:43 UTC, ashxjain commented on network/netvisor/pn_vrouterbgp.py
> +  description: The CLI command run on the target node(s).
That's just the description for the command. `returned:` and `type:` are mentioned below.

2016-09-16 13:44 UTC, ashxjain commented
ready_for_review

2016-09-16 14:04 UTC, gundalow commented on network/netvisor/pn_vrouterbgp.py
> +  description: The CLI command run on the target node(s).
Yup, you are correct. PR blindness :)

2016-09-16 14:04 UTC, gundalow approved these changes

2016-09-16 14:04 UTC, merged

2016-09-16 14:04 UTC, gundalow commented
Merged, thanks!

2016-09-16 14:12 UTC, ashxjain commented
Thanks a lot @gundalow !