Added support for dnos6_config module
ansible/ansible-modules-core pull request #4824
Opened 2016-09-13 22:56 UTC by skg-net

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
- modules/core/network/dnos6/dnos6_config

##### ANSIBLE VERSION
- ansible 2.2.0 (devel a1947401ba) last updated 2016/09/08 17:44:28 (GMT -700) lib/ansible/modules/core: (detached HEAD db38f0c) last updated 2016/09/08 17:44:58 (GMT -700) lib/ansible/modules/extras: (detached HEAD 8bfdcfcab2) last updated 2016/09/08 17:44:58 (GMT -700) config file = /home/skg/lothlorien/ansible.cfg configured module search path = Default w/o overrides

##### SUMMARY
- Added support for dnos9_config module to support Dell Networking OS6 devices.

2016-09-14 03:25 UTC, gregdek commented
Thanks @skg-net for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-14 14:22 UTC, skg-net commented
ready_for_review

2016-09-14 15:25 UTC, gregdek commented
Thanks @skg-net for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-14 16:56 UTC, gundalow commented on network/dnos6/dnos6_config.py
> +        device config parser. This argument is mutually exclusive with O(src).
There isn't a `O(...)`

`I(src)` for italics
or `C(...)` for code

2016-09-14 16:57 UTC, gundalow commented on network/dnos6/dnos6_config.py
> +        exclusive with O(lines).
I(...)

2016-09-14 16:59 UTC, gundalow commented on network/dnos6/dnos6_config.py
> +      - The C(config) argument allows the playbook desginer to supply
designer

2016-09-14 17:03 UTC, gundalow commented on network/dnos6/dnos6_config.py
> +        stack if a changed needs to be made.  Just like with I(before) this
s/changed/change/

2016-09-14 17:06 UTC, gundalow commented
needs_revision

2016-09-14 18:49 UTC, skg-net commented on network/dnos6/dnos6_config.py
> +        device config parser. This argument is mutually exclusive with O(src).
Done.

2016-09-14 18:52 UTC, skg-net commented on network/dnos6/dnos6_config.py
> +        stack if a changed needs to be made.  Just like with I(before) this
Done.

2016-09-14 18:53 UTC, gundalow commented on network/dnos6/dnos6_config.py
> +        device config parser. This argument is mutually exclusive with O(src).
I don't see a commit with the `I(...)` --> `C(...)` changes in

2016-09-14 18:53 UTC, gundalow requested changes

2016-09-14 19:09 UTC, gundalow commented
shipit

2016-09-14 19:09 UTC, gundalow approved these changes

2016-09-14 21:25 UTC, gregdek commented
Thanks again to @skg-net for this PR, and thanks @ansible/core for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-15 06:03 UTC, skg-net commented
Based the infra required for template module. We need to rework on this config module as well.
So I am closing this PR. I will create a new one once, code is ready.

2016-09-15 16:03 UTC, merged

2016-09-15 16:03 UTC, gundalow commented
Merged, thanks