Expose the reuse_fips flag on os_server
ansible/ansible-modules-core pull request #4849
Opened 2016-09-14 19:45 UTC by emonty

2016-09-14 21:25 UTC, gregdek commented
Thanks again to @emonty. This module is going into community review.

We notice that you are one of the maintainers (@emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-15 19:04 UTC, Shrews approved these changes
LGTM

2016-09-15 19:05 UTC, j2sol commented on cloud/openstack/os_server.py
> +    reuse_fips = module.params['reuse_fips']
I don't see where this is actually used. Later in this function you directly access `module.params['reuse_fips']`.

Am I missing something?

2016-09-15 19:06 UTC, omgjlk reviewed
I have a question...

2016-09-15 20:03 UTC, Shrews reviewed
Ok, _NOW_ it LGTM

2016-09-15 20:04 UTC, Shrews requested changes
ignore this

2016-09-15 20:04 UTC, Shrews approved these changes

2016-09-15 20:07 UTC, merged

2016-09-19 23:35 UTC, bryfry commented
which version of shade actually uses this? I'm getting unexpected keyword argument 'reuse_fips' now.

2016-09-20 09:58 UTC, Jorge-Rodriguez commented
@Shrews I tried this with shade 1.21.1 (latest) and got the same result as @bryfry

2016-09-20 12:14 UTC, Shrews commented
Yep, this is a bug. Correct parameter name is reuse_ips. Fix coming shortly.

2016-09-20 12:21 UTC, Shrews commented
https://github.com/ansible/ansible-modules-core/pull/4939