Added support dnos9_facts module
ansible/ansible-modules-core pull request #4873
Opened 2016-09-15 18:04 UTC by skg-net

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
 - modules/core/network/dnos9/dnos9_facts

##### ANSIBLE VERSION
- ansible 2.2.0 (devel a194740) last updated 2016/09/08 17:44:28 (GMT -700) lib/ansible/modules/core: (detached HEAD db38f0c876) last updated 2016/09/08 17:44:58 (GMT -700) lib/ansible/modules/extras: (detached HEAD 8bfdcfcab2) last updated 2016/09/08 17:44:58 (GMT -700) config file = configured module search path = Default w/o overrides 

##### SUMMARY 

- Added support OS9 facts module to support Dell Networking OS9 devices.

2016-09-15 18:04 UTC, skg-net commented
@privateip @gundalow, please have look at it

2016-09-15 18:26 UTC, gundalow commented on network/dnos9/dnos9_facts.py
> +  description: All file system names availabe on the device
available

2016-09-15 18:29 UTC, gundalow requested changes
needs_revision

I notice that this is by @dhivyap, should I add @dhivyap as a maintainer for dnos*, just so it's not only you that get notified when other people start raising issues/PR

2016-09-15 21:25 UTC, gregdek commented
Thanks again to @skg-net. This module is going into community review.

We notice that you are one of the maintainers (@dhivyap, @skg-net, @privateip, @gundalow) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-15 21:42 UTC, skg-net commented on network/dnos9/dnos9_facts.py
> +  description: All file system names availabe on the device
Done. Please add @dhivyap as well.
ready_for_review

2016-09-15 21:42 UTC, skg-net commented
ready_for_review

2016-09-16 11:54 UTC, merged

2016-09-16 11:54 UTC, gundalow commented
Merged, thanks