Added support for facts module for Dell Networking OS10 device.
ansible/ansible-modules-core pull request #4879
Opened 2016-09-15 23:29 UTC by skg-net

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
- modules/core/network/dnos10/dnos10_facts

##### ANSIBLE VERSION
- ansible 2.2.0 (devel f497d771c8) last updated 2016/09/15 12:00:53 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 48d932643b) last updated 2016/09/15 12:01:19 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD aa45bd8a94) last updated 2016/09/15 12:01:19 (GMT -700)
  config file = /home/skg/lothlorien/ansible.cfg
  configured module search path = Default w/o overrides

##### SUMMARY
- Added support for facts module for Dell Networking OS10 device.

2016-09-15 23:29 UTC, skg-net commented
@gundalow @privateip , Please have a look at it.

2016-09-16 03:25 UTC, gregdek commented
Thanks again to @skg-net. This module is going into community review.

We notice that you are one of the maintainers (@dhivyap, @skg-net, @privateip, @gundalow) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-16 11:48 UTC, privateip commented on network/dnos10/dnos10_facts.py
> +import xml.etree.ElementTree as ET
need to wrap this in a try ... except block as its not part of the std lib.  see [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/junos.py#L52) for example

2016-09-16 11:50 UTC, privateip requested changes

2016-09-16 11:54 UTC, gundalow commented
needs_revision - As per Peters comments above

2016-09-16 15:25 UTC, gregdek commented
Thanks @skg-net for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-16 17:39 UTC, skg-net commented on network/dnos10/dnos10_facts.py
> +import xml.etree.ElementTree as ET
xml.etree.ElementTree is part of standard library.  I update the code as per your request.

2016-09-16 17:40 UTC, skg-net commented
ready_for_review

2016-09-16 17:54 UTC, gundalow commented on network/dnos10/dnos10_facts.py
> +import xml.etree.ElementTree as ET
`from lxml import etree as ET` reports `No module named lxml` on Python 2.6.6.
`xml.etree.ElementTree` does work on Python 2.6.6

2016-09-16 18:04 UTC, skg-net commented on network/dnos10/dnos10_facts.py
> +import xml.etree.ElementTree as ET
need to install lxml, its not part of the standard package

2016-09-16 18:06 UTC, merged

2016-09-16 18:06 UTC, gundalow commented
Merged, thanks.

I believe this is the last PR so you can go ahead and commence the renaming.