Update git.py notes
ansible/ansible-modules-core pull request #5417
Opened 2016-10-27 14:26 UTC by hyperized

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
source_control/git

##### ANSIBLE VERSION
```
n/a
```

##### SUMMARY
Added notes section about SSH-agents that can be used to avoid unnecessary password prompts.

2016-10-27 14:29 UTC, jjshoe requested changes

2016-10-27 14:29 UTC, jjshoe commented on source_control/git.py
> +    - "When working with git over SSH, it's recommended you use your SSH agent to store the keys and passwords in order for the module not to prompt the key password several times during execution"
SSH agents don't store passwords.

2016-10-27 14:29 UTC, jjshoe commented on source_control/git.py
> +    - "When working with git over SSH, it's recommended you use your SSH agent to store the keys and passwords in order for the module not to prompt the key password several times during execution"
Also, grammar could stand a significant re-work

2016-10-27 15:25 UTC, gregdek commented
Thanks @hyperized for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-28 09:25 UTC, gregdek commented
Thanks @hyperized for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-30 23:21 UTC, closed without merging