cloudformation: add .format indexes for 2.6 compatability
ansible/ansible-modules-core pull request #5552
Opened 2016-11-10 16:26 UTC by tedder

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

cloudformation

##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

Fixes #5551; the "".format() style needs to have `{0}` instead of the implied `{}` version for compatability with 2.6.

2016-11-10 16:34 UTC, ryansb commented
Looks good to me :+1:

2016-11-10 22:25 UTC, gregdek commented
Thanks again to @tedder for this PR, and thanks @tedder, @ryansb for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-11 14:35 UTC, ryansb requested changes

2016-11-11 14:35 UTC, ryansb commented on cloud/amazon/cloudformation.py
> +        eventline = 'StackEvent {0} {1} {2}'.format(e['ResourceType'], e['LogicalResourceId'], e['ResourceStatus'])
There's an even nicer (and still compatible) way to do this:

```
'StackEvent {ResourceType} {LogicalResourceId} {ResourceStatus}'.format(**e)
```

2016-11-11 14:35 UTC, ryansb commented on cloud/amazon/cloudformation.py
> +            failline = '{0} {1} {2}: {3}'.format(e['ResourceType'], e['LogicalResourceId'], e['ResourceStatus'], e['ResourceStatusReason'])
`'{ResourceType} {LogicalResourceId} {ResourceStatus}: {ResourceStatusReason}'.format(**e)`

2016-11-18 23:53 UTC, tedder commented
@ryansb I don't know how to proceed- you have to do it now?

2016-11-26 13:53 UTC, ryansb approved these changes

2016-11-26 13:53 UTC, merged