Snmp community
ansible/ansible-modules-core pull request #5586
Opened 2016-11-12 09:28 UTC by GGabriele

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
nxos_snmp_community

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
Changed how module work to make it use running config for module operations instead of cli commands. Referring to #5214

2016-11-12 09:55 UTC, GGabriele commented
@privateip  The error is due to `version_added: 2.2` on docstring while it expects 2.3, but actually those params have been introduced in 2.2.

2016-11-12 10:25 UTC, gregdek commented
Thanks @GGabriele for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-22 15:53 UTC, gundalow requested changes
needs_revision

2016-11-22 15:53 UTC, gundalow commented on network/nxos/nxos_snmp_community.py
> +        version_added: 2.2
2.3

2016-11-22 15:53 UTC, gundalow commented on network/nxos/nxos_snmp_community.py
> +        version_added: 2.2
2.3

2016-11-22 15:53 UTC, gundalow commented on network/nxos/nxos_snmp_community.py
> +        version_added: 2.2
2.3

2016-11-23 13:13 UTC, GGabriele commented
ready_for_review

2016-11-23 13:27 UTC, gundalow approved these changes

2016-11-23 16:25 UTC, gregdek commented
Thanks @GGabriele. To the current maintainers, @jedelman8, @GGabriele, @privateip, @gundalow, @qalthos please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-24 10:52 UTC, gundalow commented
@privateip @Qalthos Please review and if you are happy merge

2016-12-20 11:56 UTC, closed without merging