Examples syntax batch6
ansible/ansible-modules-core pull request #5623
Opened 2016-11-15 20:39 UTC by samdoran

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
- os_auth
- os_client_config
- os_image_facts
- os_networks_facts
- os_nova_flavor
- os_object
- os_server
- os_subnet_facts
- rax_files
- rax_files_objects
- mysql_db
- file
- uri
- cl_bond
- cl_bridge
- cl_img_install
- cl_interface
- cl_license
- cl_ports

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /Users/sdoran/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Per Ansible Core team meeitng on [2016-11-03](https://meetbot.fedoraproject.org/ansible-meeting/2016-11-03/public_core_meeting.2016-11-03-15.02.html), change syntax in EXAMPLES in Core modules to use multi-line YAML.

2016-11-15 20:52 UTC, samdoran commented on network/basics/uri.py
> +    url: http://www.example.com
Quotes are option for the `url:` parameter in the `uri` module.

2016-11-15 20:52 UTC, samdoran commented on network/basics/uri.py
> +    url: http://www.example.com
Not sure of the _exacet_ rule around this, but my testing shows it works with or without quotes and doesn't report a syntax error.

2016-11-15 22:25 UTC, gregdek commented
Thanks @samdoran for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-16 12:15 UTC, gundalow commented on network/basics/uri.py
> +- name: Queue build of a project in Jenkins:
Delete trailing `:`

2016-11-16 12:16 UTC, gundalow requested changes
needs_revision

2016-11-16 17:21 UTC, gundalow approved these changes

2016-11-16 17:24 UTC, merged