Fix #4281 Add timeout param to junos_config module
ansible/ansible-modules-core pull request #5679
Opened 2016-11-19 18:50 UTC by ganeshnalawade

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME
junos_config

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 461286f914)
```

##### SUMMARY

```
Add NETCONF RPC timeout beyond the default value of
30 seconds. Set this value to accommodate configuration
changes (commits) that might take longer than the default
timeout interval.
```

2016-11-19 22:25 UTC, gregdek commented
Thanks @ganeshnalawade for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-20 06:09 UTC, ganeshnalawade commented
@gregdek CI run passed after revision.

2016-11-21 16:25 UTC, gregdek commented
Thanks @ganeshnalawade. To the current maintainers, @privateip, @gundalow, @qalthos please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-23 16:41 UTC, gundalow commented on network/junos/junos_config.py
> +  timeout:
netconf_timeout

2016-11-23 16:41 UTC, gundalow requested changes
needs_revision

2016-11-23 17:14 UTC, ganeshnalawade commented
As per @Qalthos will check if netconf timeout can be implemented in module_utils so that it can be added to all other junos modules

2016-11-24 18:09 UTC, ganeshnalawade commented
@gundalow @Qalthos ready_for_review
Related PR https://github.com/ansible/ansible/pull/18616

2016-11-26 09:18 UTC, ganeshnalawade commented
Closing this PR, as https://github.com/ansible/ansible/pull/18634 fixes the issue

2016-11-26 09:18 UTC, closed without merging