Native YAML - files/file.py
ansible/ansible-modules-core pull request #5799
Opened 2016-12-02 13:06 UTC by Fale

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
files/file.py

##### ANSIBLE VERSION
```
2.2
```

##### SUMMARY
Make YAML code use the native style

@gundalow

2016-12-02 15:41 UTC, gundalow reviewed
Unsure about with_items rewrite

2016-12-02 15:45 UTC, gundalow commented on files/file.py
> -    - { src: 'x', dest: 'y' }
I'm going to say that rewriting the `write_items` section here decreases readability, can you please revert that bit.

2016-12-02 15:45 UTC, gundalow requested changes
needs_revision

2016-12-02 16:25 UTC, gregdek commented
Thanks @Fale for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-12-04 10:48 UTC, gundalow approved these changes

2016-12-04 10:48 UTC, merged