Improve quotes
ansible/ansible-modules-core pull request #5819
Opened 2016-12-04 21:43 UTC by Fale

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
network/*

##### ANSIBLE VERSION
```
2.2
```

##### SUMMARY
Remove unnecessary quotes, and other small changes

@gundalow

2016-12-04 22:25 UTC, gregdek commented
Thanks @Fale for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-12-05 04:11 UTC, gundalow requested changes

2016-12-05 04:11 UTC, gundalow commented on cloud/azure/azure.py
> +      name: ben-Winows-23
Winows or Windows?

2016-12-05 04:11 UTC, gundalow commented on cloud/azure/azure_rm_virtualmachine.py
> +      sku: 7.1
Should these be ints or strings?

2016-12-07 13:45 UTC, closed without merging